# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

default_docker: &default_docker
  docker:
      - image: cimg/base:2020.01

commands:
  echo_text:
    description: echo some text
    parameters:
      text:
        type: string
        default: some text
    steps:
      - run: echo << parameters.text >>
      - run:
          name: notify job failur
          command: curl --data "{"error":"echo job failed"}" http://example.com/error_logs
          when: on_fail

jobs:

  configure_infrastructure:
    docker:
      - image: cytopia/ansible
    environment:
      ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "f8:9f:df:db:12:e1:dd:87:75:95:0b:f6:96:89:e7:22"
      - run:
          name: Configure server
          command: |
            ansible-playbook -i ansible/inventory.txt ansible/main.yml

  smoke_test:
      <<: *default_docker
      environment:
        URL: https://google.com/
      steps:
        - run:
            name: smoke test.
            command: |
              if curl -s --head $URL
              then
               return 0
              else
               return 1
              fi

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - configure_infrastructure
      - smoke_test:
          requires:
            - configure_infrastructure
